
AppBundle\Entity\Price:
    properties:
        type:
            - NotNull: ~
            - Choice:
                choices: [ less_than_12, for_all ]

        value:
            - NotNull: ~
            - Type: numeric
            - GreaterThanOrEqual:
                value: 0